# Generated by Django 5.0.1 on 2024-04-10 05:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=100, null=True, verbose_name='Name')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated DateTime')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
