# Generated by Django 5.0.1 on 2024-04-10 05:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_alter_postmodel_body_alter_postmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
    ]
