# Generated by Django 5.0.1 on 2024-04-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0003_alter_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Count'),
        ),
    ]
